### ISSUE TITLE
OpenCV Error: Assertion failed

### ISSUE THREAD

**Issue by smarquard** [LectureTracking/trackhd#15]
----------------------------------------
Stage [3 of 3] - Virtual Cinematographer
----------------------------------------

baqwa-720p.mp4
BoardSegment-baqwa-720pmp4
875967064
OpenCV: FFMPEG: tag 0x34363258/'X264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x00000021/'!???'
OpenCV: FFMPEG: tag 0x34363258/'X264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x00000021/'!???'
[flv @ 0x18e4b40] AMF_DATA_TYPE_STRING parsing failed
Input frame resolution: Width=3840  Height=2160 of nr#: 1948
Input codec type: 
Video Duration (Seconds): 67
FPS: 29
End of video file
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /srv/dev/opencv/modules/core/src/matrix.cpp, line 522
terminate called after throwing an instance of 'cv::Exception'
  what():  /srv/dev/opencv/modules/core/src/matrix.cpp:522: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

**Comment by charlesfitzhenry** [comment]
Hopefully, the last commit fixes this issue but will leave it open for more testing until we can be sure it's resolved.

**Comment by smarquard** [comment]
Looks good now - the video that failed originally now processes successfully.

**Comment by charlesfitzhenry** [comment]
Issue resolved by @smarquard review
