### ISSUE TITLE
Output framerate and duration differs from source

### ISSUE THREAD

**Issue by smarquard** [LectureTracking/trackhd#19]
ffprobe presenter-MAM1000W-20160811.mp4 shows:

 Duration: 00:50:00.01, start: 0.033367, bitrate: 5655 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 5652 kb/s, 29.95 fps, 29.97 tbr, 90k tbn, 180k tbc (default)

Output processed to 1920x1080p shows:

 Duration: 00:51:38.28, start: 0.000000, bitrate: 1925 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 1922 kb/s, 29 fps, 29 tbr, 14848 tbn, 58 tbc (default)

It looks like the framerate has been scaled down so the duration is incorrect, and possibly the frame timestamp information has been dropped (which is important if the source is not a fixed framerate).

**Comment by charlesfitzhenry** [comment]
This issue was addressed in commit 1053e1334f235fac6ebebcfe72ece9849a76f1a5 and will leave this issue open for further testing, to ensure problem is resolved.

**Comment by smarquard** [comment]
This is not quite working. On a long 10G 4K video:

input video is 3:55:00, frame count 422388, frame rate 29.97003 (mkv container)
result video is 3:54:53, frame count 422388, frame rate 29.97 (mp4 container)
