### ISSUE TITLE
Large repo size

### ISSUE THREAD

**Issue by smarquard** [LectureTracking/trackhd#20]
The repo is about 89M to check out, when it should be tiny:

~ $ git clone https://github.com/LectureTracking/trackhd.git
Cloning into 'trackhd'...
remote: Counting objects: 604, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 604 (delta 9), reused 0 (delta 0), pack-reused 578
Receiving objects: 100% (604/604), 89.01 MiB | 169.00 KiB/s, done.
Resolving deltas: 100% (333/333), done.

There are some techniques for cleaning up git history that you could look into, otherwise you may want to consider deleting and re-creating the repo with a clean commit of source only.

**Comment by charlesfitzhenry** [comment]
This issue has been resolved in commit 7a43daf0b093744fbacebecef44f3814a223a389.

**Comment by smarquard** [comment]
Looks good, thanks!
```
# git clone https://github.com/LectureTracking/trackhd.git
Cloning into 'trackhd'...
remote: Counting objects: 478, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 478 (delta 36), reused 10 (delta 10), pack-reused 365
Receiving objects: 100% (478/478), 217.63 KiB | 133 KiB/s, done.
Resolving deltas: 100% (271/271), done.

# du -hs trackhd/
652K    trackhd/
```

**Comment by charlesfitzhenry** [comment]
I used the following command to check the file size. Gave similar results.
`$ git count-objects -vH
`

> count: 3
size: 882 bytes
in-pack: 475
packs: 1
size-pack: 231.07 KiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
