### ISSUE TITLE
Add description and website link to github project

### ISSUE THREAD

**Issue by smarquard** [LectureTracking/trackhd#21]
Please edit github project info - currently showing "No description, website, or topics provided." at the top. Should have a short description and link to http://track4k.co.za

**Comment by MTKhatieb** [comment]
Added:
-> Name
-> Description / Bio
-> Company (UCT)
-> Location (Cape Town South Africa)
-> Website Link

**Comment by smarquard** [comment]
This is the missing description that I'm referring to:

![image](https://cloud.githubusercontent.com/assets/5888197/24361976/aa20061e-130b-11e7-84b1-a8250dc2307f.png)

**Comment by MTKhatieb** [comment]
Misunderstood where the description should have gone.
Have since addressed the problem.
