### ISSUE TITLE
Start panning from centre rather than left of image

### ISSUE THREAD

**Issue by smarquard** [LectureTracking/trackhd#24]
Track4K always starts panning from the very left of the image.

If there is an identified presenter already, the first frame should be there (rather than pan to the presenter).

if there's no identified presenter in the first frame, then start in the horizontal centre of the image.

**Comment by charlesfitzhenry** [comment]
This issue is hopefully resolved in d51f45e5b0cd2866d401c355f65374fb6afe4bdd. Needs to be tested more.

**Comment by smarquard** [comment]
That doesn't seem to work; there's no difference in the tracking output before and after this change. If it was working successfully, then you'd expect to see the first crop co-ordinates in the crop data file have an x value of 3840/2 = 1920 for a 4K input video. Instead it's still 0.

Also I guess you didn't mean to commit presenter-crop.txt ?

**Comment by charlesfitzhenry** [comment]
My version of cropvid is not working well. For a 40-second test input video, it outputs a 9-minute video, which doesn't move the cropping window, although the cropping window is centred. It is hard to tell if it's working. @smarquard please, would you test this on your version again and let me know if it works.

**Comment by smarquard** [comment]
Thanks. Please send me the test video you're using.

**Comment by charlesfitzhenry** [comment]
[vid.zip](https://github.com/LectureTracking/trackhd/files/1464667/vid.zip)

**Comment by smarquard** [comment]
The panning from the centre seems to work correctly now on our test videos. I think the issue with processing the mp4 with cropvid is to do with the container format and timestamps, which I'll look into separately.
