### ISSUE TITLE
Build cropvid fails on clean system

### ISSUE THREAD

**Issue by CGreweling** [LectureTracking/trackhd#36]
Building cropvid as described in the docs on a clean ubuntu 16.04 fails:

Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
cropvid.c:36:34: fatal error: libavfilter/avfilter.h: Datei oder Verzeichnis nicht gefunden

**Comment by smarquard** [comment]
@slampunk, can you take a look at this?

**Comment by slampunk** [comment]
[Pull request](https://github.com/LectureTracking/trackhd/pull/37) created. Building of cropvid completes without issue on a clean Ubuntu 16.04 when using the updated instructions in README.md

**Comment by charlesfitzhenry** [comment]
Have merged changes of the pull request back into the master branch

**Comment by CGreweling** [comment]
Works, thank you!
