### ISSUE TITLE
using track4k with live stream from video conference software

### ISSUE THREAD

**Issue by jcherrabi** [LectureTracking/trackhd#42]
Hello there,
can you please let me know how to apply track4k on a live video stream on ubuntu server that is hosting an open source video conference software?

thank you.
Jay

**Comment by jcherrabi** [comment]
is there a guide on how to intergrade this with bigbluebutton ?

**Comment by smarquard** [comment]
track4k is not designed to work with a live stream. It processes a complete, recorded 4K video afterwards.

**Comment by jcherrabi** [comment]
Hello smarquard, 
Thank you for your answer, sure I understand that, so my question now is how could I integrate this and apply it to bigbluebutton recorded session? is there a guide I can follow to have it process recorded video on a server side?
thank you :)
